version: "3"
services:
  front:
    build: .
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ./volune:/usr/share/nginx/html
    ports:
      - 8084:80
    restart: unless-stopped
